---
- name: Include secret var file
  include_vars:
    file: secrets.yml

- name: Check installed packages
  package_facts:
    manager: auto

- name: Install and start Docker if needed
  block:
    - name: Install epel-release, yum-utils
      yum:
        name: ['epel-release', 'yum-utils']
        state: latest
        update_cache: true

    - name: Install python-pip
      yum:
        name: python-pip
        state: latest
        update_cache: true

    - name: Pip install docker-py
      pip:
        name: docker-py
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Enable Docker repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: '0'

    - name: Install Docker
      yum:
        name: docker-ce
        state: latest

  when: "'docker-ce' not in ansible_facts.packages"
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Run MariaDB server
  docker_container:
    env:
      MYSQL_USER: "{{ mariadb_user }}"
      MYSQL_PASSWORD: "{{ mariadb_password }}"
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"
    image: "mariadb:{{ mariadb_version}}"
    name: "{{ mariadb_container_name }}"
    ports:
      - "{{ mariadb_port }}:3306"
    pull: true
    restart_policy: always
    state: started
  become: yes

    